### ISSUE TITLE
Frame length confusion

### ISSUE THREAD

**Issue by milloni** [Jeija/renard-spec#1]
I think there is confusion here regarding #define's used for frame sizes. If I understand the semantics correctly, `sfx_ul_encoded` represents a raw unit of data (I don't want to call this a frame since it's actually 3 frames). If that's true, then `SFX_UL_MAX_FRAMELEN` is the length of the whole frame, including the preamble.

However, `SFX_UL_MAX_FRAMELEN` is defined as 24 which corresponds to the frame length *minus* the preamble (23.5 excactly). This means that `sfx_ul_encoded` no longer represnts the raw unit of data.

librenard uses this semantic throughout all computations except in one place

```
uint8_t frame_plain[SFX_UL_MAX_FRAMELEN - SFX_UL_PREAMBLELEN_NIBBLES / 2];
```

where it assumes `SFX_UL_MAX_FRAMELEN` is the size of the entire frame. This leads to the `frame_plain` buffer being smaller than needed to process all data. So for example when this `sfx_ul_encoded` object:

```
00000000: bd41 4141 4141 417f ff41 5d41 4141 4141  .AAAAAA..A]AAAAA
00000010: 4141 3241 417f 6c00 4000 0041 4141 4141  AA2AA.l.@..AAAAA
00000020: 3041 4241 41ff 4100 617f 6c50 5c41 4141  0ABAA.A.a.lP\AAA
00000030: 4141 4141 0041 4241 41ff 2000 4141 4141  AAAA.ABAA. .AAAA
00000040: 4141 4100 4150 4141 2f                   AAA.APAA/
```

(use `xxd -r` to convert back to binary), it causes when out-of-bounds write on `frame_plain`:

```
=================================================================
==30935==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xff88f9b6 at pc 0xf79e27f6 bp 0xff88f8a8 sp 0xff88f480
WRITE of size 24 at 0xff88f9b6 thread T0
    #0 0xf79e27f5  (/usr/lib/i386-linux-gnu/libasan.so.3+0x547f5)
    #1 0x565f6f8b in sfx_uplink_decode (/targets/librenard_harness/harness_uplink+0x2f8b)
    #2 0x565f5265 in main (/targets/librenard_harness/harness_uplink+0x1265)
    #3 0xf77ee285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)
    #4 0x565f4c10  (/targets/librenard_harness/harness_uplink+0xc10)

Address 0xff88f9b6 is located in stack of thread T0 at offset 182 in frame
    #0 0x565f6b57 in sfx_uplink_decode (/targets/librenard_harness/harness_uplink+0x2b57)

  This frame has 3 object(s):
    [32, 37) 'mac'
    [96, 116) 'packet'
    [160, 182) 'frame_plain' <== Memory access at offset 182 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/usr/lib/i386-linux-gnu/libasan.so.3+0x547f5) 
Shadow bytes around the buggy address:
  0x3ff11ee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ff11ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ff11f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ff11f10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ff11f20: f1 f1 f1 f1 05 f4 f4 f4 f2 f2 f2 f2 00 00 04 f4
=>0x3ff11f30: f2 f2 f2 f2 00 00[06]f4 f3 f3 f3 f3 00 00 00 00
  0x3ff11f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ff11f50: 00 00 f1 f1 f1 f1 00 00 f4 f4 f2 f2 f2 f2 00 00
  0x3ff11f60: 00 f4 f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 01
  0x3ff11f70: f4 f4 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
  0x3ff11f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==30935==ABORTING
```

I got this output by building librenard with `CFLAGS=-fsanitize=address`.

I found this bug by fuzzing with lcamtuf's american fuzzy lop http://lcamtuf.coredump.cx/afl/

Thanks
milloni

**Comment by milloni** [comment]
Sorry, this should have gone to https://github.com/Jeija/librenard :/

**Comment by Jeija** [comment]
Sorry for not answering for ages, but you are of course perfectly right. I finally fixed this bug in `librenard`, see https://github.com/Jeija/librenard/commit/4abc00299b025c8428987ef7f10ff2449a243940. Thank you for reporting :+1: !
